<?php

namespace Todo\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TachesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TachesRepository extends EntityRepository
{
}
